# Prédiction du score d'addiction aux réseaux sociaux
## Modèle de Machine Learning - Random Forest 

dataset utilisé: Student Social Media Addiction
objectif : prédire score d'addiction (variable Addicted_score) d'un individu
Lea Carminati 09/03/2026

## 1 Importation bibliothèques

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import (mean_absolute_error, mean_squared_error,
                             r2_score)


print("Bibliothèques importées avec succès")

Bibliothèques importées avec succès

## 2 Chargement données et aperçu

In [5]:
df = pd.read_csv("BDD_initial\Students Social Media Addiction.csv")

print( df.shape[0], "lignes", df.shape[1], "colonnes")
print("minimum variable cible Addicted_Score:", df['Addicted_Score'].min())
print("maximum variable cible Addicted_Score:", df['Addicted_Score'].max())
df.head(10)

705 lignes 13 colonnes
minimum variable cible Addicted_Score: 2
maximum variable cible Addicted_Score: 9

,Student_ID,Age,Gender,Academic_Level,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Affects_Academic_Performance,Sleep_Hours_Per_Night,Mental_Health_Score,Relationship_Status,Conflicts_Over_Social_Media,Addicted_Score
0,1,19,Female,Undergraduate,Bangladesh,5.2,Instagram,Yes,6.5,6,In Relationship,3,8
1,2,22,Male,Graduate,India,2.1,Twitter,No,7.5,8,Single,0,3
2,3,20,Female,Undergraduate,USA,6.0,TikTok,Yes,5.0,5,Complicated,4,9
3,4,18,Male,High School,UK,3.0,YouTube,No,7.0,7,Single,1,4
4,5,21,Male,Graduate,Canada,4.5,Facebook,Yes,6.0,6,In Relationship,2,7
5,6,19,Female,Undergraduate,Australia,7.2,Instagram,Yes,4.5,4,Complicated,5,9
6,7,23,Male,Graduate,Germany,1.5,LinkedIn,No,8.0,9,Single,0,2
7,8,20,Female,Undergraduate,Brazil,5.8,Snapchat,Yes,6.0,6,In Relationship,2,8
8,9,18,Male,High School,Japan,4.0,TikTok,No,6.5,7,Single,1,5
9,10,21,Female,Graduate,South Korea,3.3,Instagram,No,7.0,7,In Relationship,1,4

Informations générales

In [8]:
print(df.dtypes)
print(df.isnull().sum())
df.describe()

Student_ID                        int64
Age                               int64
Gender                              str
Academic_Level                      str
Country                             str
Avg_Daily_Usage_Hours           float64
Most_Used_Platform                  str
Affects_Academic_Performance        str
Sleep_Hours_Per_Night           float64
Mental_Health_Score               int64
Relationship_Status                 str
Conflicts_Over_Social_Media       int64
Addicted_Score                    int64
dtype: object
Student_ID                      0
Age                             0
Gender                          0
Academic_Level                  0
Country                         0
Avg_Daily_Usage_Hours           0
Most_Used_Platform              0
Affects_Academic_Performance    0
Sleep_Hours_Per_Night           0
Mental_Health_Score             0
Relationship_Status             0
Conflicts_Over_Social_Media     0
Addicted_Score                  0
dtype: int64

,Student_ID,Age,Avg_Daily_Usage_Hours,Sleep_Hours_Per_Night,Mental_Health_Score,Conflicts_Over_Social_Media,Addicted_Score
count,705.000000,705.000000,705.000000,705.000000,705.000000,705.000000,705.000000
mean,353.000000,20.659574,4.918723,6.868936,6.226950,2.849645,6.436879
std,203.660256,1.399217,1.257395,1.126848,1.105055,0.957968,1.587165
min,1.000000,18.000000,1.500000,3.800000,4.000000,0.000000,2.000000
25%,177.000000,19.000000,4.100000,6.000000,5.000000,2.000000,5.000000
50%,353.000000,21.000000,4.800000,6.900000,6.000000,3.000000,7.000000
75%,529.000000,22.000000,5.800000,7.700000,7.000000,4.000000,8.000000
max,705.000000,24.000000,8.500000,9.600000,9.000000,5.000000,9.000000

## 3 Prétraitement des données

Avant d'entraîner le modèle il faut encoder les variables categorielles ( transformer de texte en nombre), supprimer les colonnes qui nous disent rien sur la prediction qu'on veut faire (non predictif) et séparer les données (cible y et features X)

In [ ]:
df_ml=df.copy() #copie de travail

df_ml = df_ml.drop(columns =['Student_ID'])